### PR TITLE
Lodash 4 compatibility (next)

### PR DESCRIPTION
**Pull request by jgonggrijp**
This is #585 redone for the `next` branch.

Installing the packages seems to have altered `dist/backbone-relational.js` and `dist/backbone-relational.js.map` as a side effect (probably the `build` script). It was not clear to me whether this should be the case, nor whether the contents of `dist` should always reflect the latest version of the code.

What *should* have happened to those files? If necessary, I can add another commit, or change an earlier commit and force-push, or make a separate branch and submit a new PR.

### CODE REVIEW

**Comment by jgonggrijp** [comment]
@bpatram Thanks for merging!

**Comment by pombadev** [comment]
Any timeline of releasing this? Instead of waiting for v0.11.0 or v0.12.0, would you consider releasing it?
Our company decided to update lodash to v4 and ever since this has been simply a major pain for us.

Please don't take it in a wrong way. I'm not demanding a release, just politely asking.
Thanks.

**Comment by bpatram** [comment]
@pjmp @jgonggrijp I haven't actually been added to the NPM package owners yet; stand by.

---

@PaulUithol Can you add me as an owner to the NPM package? 

`npm owner add bpatram backbone-relational` (https://docs.npmjs.com/cli/owner)

**Comment by PaulUithol** [comment]
Hey, thanks for the ping - missed the email initially I think. Am traveling/don't have any dev on this machine, but there is an option to add 'maintainers' via npmjs.com - could you let me know if that works/is sufficient?

**Pull request merged**
