### PR TITLE
Do not pass |arguments| to other functions

### PR DESCRIPTION
**Pull request by NekR**
Chrome does not optimize functions which passed |arguments| object as a argument to other functions.

Also it's good to avoid try...catch/finally statements in hot functions if possible.

### CODE REVIEW

**Comment by philfreo** [comment]
I'm all about replacing `apply` with `call` where the argument list is fixed & known, but I'm not sure it's really worth the complexity to do introduce all these loops, etc.

**Comment by NekR** [comment]
Yes, changing ```apply``` to ```call``` would be better. About "complexity worth" see here https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments

**Comment by NekR** [comment]
Also see this for performance tests http://jsperf.com/arguments-to-array/5
Method 5 is 10 times faster on my machine than method 1 or 2.

**Comment by philfreo** [comment]
IMO that's not the most relevant jsperf. All you're doing is measuring speeds of different methods of returning an array from an argument list -- but that that's not the true goal of the code you're optimizing.

Regardless, my point is that this introduces more code complexity whereas if the argument list is fixed and known (isn't it?) then just use `call`.

**Comment by NekR** [comment]
> IMO that's not the most relevant jsperf. All you're doing is measuring speeds of different methods of returning an array from an argument list -- but that that's not the true goal of the code you're optimizing.

I you think what that jsperf is not relevant then you could fine one which is. I do not understand how returning of array (it's always array) breaks relevance of that test. Key issues there is passing ```arguments``` object to other functions.

> Regardless, my point is that this introduces more code complexity whereas if the argument list is fixed and known (isn't it?) then just use call.

If you think that there are places where ```call``` might be used then it's. I think you can remove that "complexity code" in future and put there ```call``` invokation.

In the mean time, I do not understand how that "code complexity" related you end user which uses this library end expect it to be fast.

**Comment by bpatram** [comment]
While I admire the effort put towards these optimizations I agree that they add more complexity than it's worth. Unless the performance a dramatically improved I am not going to merge this in. I think there are better ways and other optimizations we can make that would be cleaner, clearer, and less complex.

**Comment by NekR** [comment]
That is your choice.

**Pull request closed without merging**
